#!/bin/sh
#PBS -m abe
#PBS -S /bin/bash

RSCRIPT='/apps/R2101/bin/Rscript --vanilla'
MIFFIT=`$RSCRIPT -e 'cat(system.file("scripts/miffit.R",package="mpifarm"))'`
SCRATCHDIR=/scratch/kingaa
MODELSTEM=cholmodel
OPTIONS="filter.q=TRUE cooling.factor=0.99 max.fail=100 init.disp=4 Np=1000 nreps=2 nmifs=160 gran=20"

cd $PBS_O_WORKDIR
lamboot -v $PBS_NODEFILE
$RSCRIPT $MIFFIT $OPTIONS jobname=\"$PBS_JOBNAME\" modelStem=\"$MODELSTEM\" scratchdir=\"$SCRATCHDIR\"
lamhalt -v
