#!/bin/sh
#PBS -N test
#PBS -m abe
#PBS -M kingaa@umich.edu
#PBS -lnodes=6:ppn=4
#PBS -S /bin/bash

R_EXE='/apps/R281/bin/Rscript --vanilla'
SCRATCHDIR=/scratch/kingaa
MODELSTEM=tps_eltor

cd $PBS_O_WORKDIR
lamboot -v $PBS_NODEFILE
$R_EXE miffit.R filter.q=FALSE cooling.factor=0.99 max.fail=100 init.disp=5 nparticles=1000 nreps=1 nmifs=6 gran=2 jobname=\"$PBS_JOBNAME\" modelStem=\"$MODELSTEM\" scratchdir=\"$SCRATCHDIR\"
lamhalt -v
